# Generated by Django 6.0.5 on 2026-07-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('on_pickup', 'On a pickup'), ('offline', 'Offline')], db_index=True, default='offline', max_length=15)),
                ('current_latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('service_radius_km', models.FloatField(default=5.0)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], db_index=True, default='unverified', max_length=15)),
                ('completed_deliveries', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('quantity_kg', models.FloatField()),
                ('estimated_servings', models.PositiveIntegerField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_at', models.DateTimeField()),
                ('pickup_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to agent'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('expired', 'Expired - reassigning')], db_index=True, default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('food_category', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed')], max_length=10)),
                ('storage_condition', models.CharField(choices=[('refrigerated', 'Refrigerated'), ('room_temperature', 'Room temperature'), ('hot_held', 'Kept hot/warm')], default='room_temperature', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified by agent'), ('rejected', 'Rejected - unsafe')], db_index=True, default='unverified', max_length=15)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('pickup_address', models.CharField(max_length=300)),
                ('delivery_address', models.CharField(blank=True, max_length=300)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_donations', to='donations.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('expired', 'Expired'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.agent')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='donations.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('recipient_type', models.CharField(choices=[('ngo', 'NGO'), ('shelter', 'Shelter'), ('orphanage', 'Orphanage'), ('old_age_home', 'Old age home'), ('community_kitchen', 'Community kitchen'), ('other', 'Other')], default='other', max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('capacity_people', models.PositiveIntegerField(help_text='Approx. number of people this recipient can serve per delivery.')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.recipient'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_donated_kg', models.FloatField(default=0)),
                ('cuisine_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('street_food', 'Street Food'), ('fast_food', 'Fast Food'), ('north_indian', 'North Indian'), ('south_indian', 'South Indian'), ('chinese', 'Chinese'), ('continental', 'Continental'), ('other', 'Other')], default='other', max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('preferred_pickup_window', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.restaurant'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars for the restaurant.', null=True)),
                ('agent_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars for the delivery agent.', null=True)),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='donations.donation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('restaurant_rating__isnull', True), models.Q(('restaurant_rating__gte', 1), ('restaurant_rating__lte', 5)), _connector='OR'), name='rating_restaurant_1_to_5'), models.CheckConstraint(condition=models.Q(('agent_rating__isnull', True), models.Q(('agent_rating__gte', 1), ('agent_rating__lte', 5)), _connector='OR'), name='rating_agent_1_to_5')],
            },
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('closing_time__gt', models.F('opening_time'))), name='restaurant_closing_after_opening'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'pickup_deadline'], name='donations_d_status_77b79b_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_deadline__gt', models.F('prepared_at'))), name='donation_deadline_after_prepared'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='donation_quantity_positive'),
        ),
    ]
